version: '2'
services:
  db:
    image: postgres
    container_name: strongs_de_db
    networks:
      - back-end
  web:
    build: .
    container_name: strongs_de_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    environment:
      VIRTUAL_HOST: test2.wordsabout.de
      VIRTUAL_PORT: 8000
    depends_on:
      - db
    networks:
      - nginx-proxy
      - back-end

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  back-end:
    driver: bridge
